package com.example.person;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630224
 * 2017-11-08T19:06:47.675-05:00
 * Generated source version: 3.1.5.redhat-630224
 * 
 */
@WebServiceClient(name = "Person", 
                  wsdlLocation = "file:/home/emunoz/Documents/CEE/01969708/rest-soap-karaf/src/main/resources/wsdl/Person.wsdl",
                  targetNamespace = "http://example.com/Person/") 
public class Person extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example.com/Person/", "Person");
    public final static QName PersonSOAP = new QName("http://example.com/Person/", "PersonSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/emunoz/Documents/CEE/01969708/rest-soap-karaf/src/main/resources/wsdl/Person.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Person.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/emunoz/Documents/CEE/01969708/rest-soap-karaf/src/main/resources/wsdl/Person.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Person(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Person(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Person() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Person(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Person(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Person(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PersonOperation
     */
    @WebEndpoint(name = "PersonSOAP")
    public PersonOperation getPersonSOAP() {
        return super.getPort(PersonSOAP, PersonOperation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonOperation
     */
    @WebEndpoint(name = "PersonSOAP")
    public PersonOperation getPersonSOAP(WebServiceFeature... features) {
        return super.getPort(PersonSOAP, PersonOperation.class, features);
    }

}
