
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.person;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630224
 * 2017-11-08T19:06:47.628-05:00
 * Generated source version: 3.1.5.redhat-630224
 * 
 */

@javax.jws.WebService(
                      serviceName = "Person",
                      portName = "PersonSOAP",
                      targetNamespace = "http://example.com/Person/",
                      wsdlLocation = "file:/home/emunoz/Documents/CEE/01969708/rest-soap-karaf/src/main/resources/wsdl/Person.wsdl",
                      endpointInterface = "com.example.person.PersonOperation")
                      
public class PersonSOAPImpl implements PersonOperation {

    private static final Logger LOG = Logger.getLogger(PersonSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.example.person.PersonOperation#newOperation(com.example.person.PersonType  person )*
     */
    public java.lang.String newOperation(com.example.person.PersonType person) { 
        LOG.info("Executing operation newOperation");
        System.out.println(person);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
